

/*======== CODE GENERATED BY mkgc ========*/


/*******************
 * 
 *    Next comes the dependencies flags; their sintax is:
 *        gc_<father>_<son>_dep
 * 
 *******************/



/*
 void *gc_get_tsk();
 * ------------------------------
 * MACRO !!
 * Returns    : Pointer to an allocated tsk node.
 * Global     : gc_l.
 * Comments   : takes a node of tsk type from gc.
 *
 * ---------------------------- */

# ifdef DEBUG
void *get_tsk();
 * ------------------------------
 * Returns    : Pointer to an allocated tsk node.
 * Global     : gc_l.
 * Comments   : takes a node of tsk type from gc. NOT A MACRO: only for debugging.
 *
 * ---------------------------- */
# endif 

/*
 void *gc_get_fun();
 * ------------------------------
 * MACRO !!
 * Returns    : Pointer to an allocated fun node.
 * Global     : gc_l.
 * Comments   : takes a node of fun type from gc.
 *
 * ---------------------------- */

# ifdef DEBUG
void *get_fun();
 * ------------------------------
 * Returns    : Pointer to an allocated fun node.
 * Global     : gc_l.
 * Comments   : takes a node of fun type from gc. NOT A MACRO: only for debugging.
 *
 * ---------------------------- */
# endif 

/*
 void *gc_get_num();
 * ------------------------------
 * MACRO !!
 * Returns    : Pointer to an allocated num node.
 * Global     : gc_l.
 * Comments   : takes a node of num type from gc.
 *
 * ---------------------------- */

# ifdef DEBUG
void *get_num();
 * ------------------------------
 * Returns    : Pointer to an allocated num node.
 * Global     : gc_l.
 * Comments   : takes a node of num type from gc. NOT A MACRO: only for debugging.
 *
 * ---------------------------- */
# endif 

/*
 void gc_put_tsk( void *el );
 * ------------------------------
 * MACRO !!
 * Returns    :
 * Global     : gc_l.
 * Comments   : inserts a node of tsk type into gc.
 *
 * ---------------------------- */

/*
 void gc_put_fun( void *el );
 * ------------------------------
 * MACRO !!
 * Returns    :
 * Global     : gc_l.
 * Comments   : inserts a node of fun type into gc.
 *
 * ---------------------------- */

/*
 void gc_put_num( void *el );
 * ------------------------------
 * MACRO !!
 * Returns    :
 * Global     : gc_l.
 * Comments   : inserts a node of num type into gc.
 *
 * ---------------------------- */



/*===== END OF CODE GENERATED BY mkgc ====*/

