

/*======== CODE GENERATED BY mkgc ========*/

typedef struct {
   list_list_tp tsk; /* tsk list */ 
   list_list_tp fun; /* fun list */ 
   list_list_tp num; /* num list */ 
} gc_type;


# define GC_TSK 0

# define GC_FUN 1

# define GC_NUM 2

# define GC_NLISTS 3


/*===== END OF CODE GENERATED BY mkgc ====*/

