/******* CODE GENERATED BY mkgmm **************/

/*
 * ********** MACROS FOR tsk NODES **********
 */
# ifdef DEBUG
#   define tsk_Malloc()   tsk_malloc()
# else
#   define tsk_Malloc() \
     ((gmm_mcr_aux = get_vadd()), \
     ( (gmm_tsk_l.nodes--)  \
        ? (gmm_tsk_l.next_nd = (gmm_mcr_aux2 =gmm_tsk_l.next_nd)+(gmm_tsk_l.nd_size), \
           vadd_map(gmm_mcr_aux,gmm_mcr_aux2) ) \
        : (gmm_mcr_aux2=gmm_tsk_malloc(),vadd_map(gmm_mcr_aux,gmm_mcr_aux2))  ))
#endif

# define tsk_is_full()\
     (gmm_tsk_l.nodes==0)

/*
 * ********** MACROS FOR fun NODES **********
 */
# ifdef DEBUG
#   define fun_Malloc()   fun_malloc()
# else
#   define fun_Malloc() \
     ((gmm_mcr_aux = get_vadd()), \
     ( (gmm_fun_l.nodes--)  \
        ? (gmm_fun_l.next_nd = (gmm_mcr_aux2 =gmm_fun_l.next_nd)+(gmm_fun_l.nd_size), \
           vadd_map(gmm_mcr_aux,gmm_mcr_aux2) ) \
        : (gmm_mcr_aux2=gmm_fun_malloc(),vadd_map(gmm_mcr_aux,gmm_mcr_aux2))  ))
#endif

# define fun_is_full()\
     (gmm_fun_l.nodes==0)

/*
 * ********** MACROS FOR num NODES **********
 */
# ifdef DEBUG
#   define num_Malloc()   num_malloc()
# else
#   define num_Malloc() \
     ((gmm_mcr_aux = get_vadd()), \
     ( (gmm_num_l.nodes--)  \
        ? (gmm_num_l.next_nd = (gmm_mcr_aux2 =gmm_num_l.next_nd)+(gmm_num_l.nd_size), \
           vadd_map(gmm_mcr_aux,gmm_mcr_aux2) ) \
        : (gmm_mcr_aux2=gmm_num_malloc(),vadd_map(gmm_mcr_aux,gmm_mcr_aux2))  ))
#endif

# define num_is_full()\
     (gmm_num_l.nodes==0)

/******* END OF CODE GENERATED BY mkgmm *******/

